language: python
python:
  - "2.7"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests
script:
    # or py.test for Python versions 3.5 and below
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  - coverage run --source=home manage.py test home
after_success:
  - coveralls
